# Generated by Django 4.2.20 on 2025-04-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default=1, upload_to='movie/'),
            preserve_default=False,
        ),
    ]
